# .codex.yaml
context:
  purpose: "Crypto futures + reserves NAV system"
  focus:
    - Quant trading stability
    - Risk management
    - Firestore + Streamlit dashboard sync
    - Reserve integration (XAUT, USDC)
    - Test coverage for NAV and order routing
rules:
  - no speculative refactors
  - maintain supervisor runtime compatibility
  - ensure all scripts pass py_compile
