# Keep defaults otherwise; this config narrows scope to stable, lintable code.

[lint]
exclude = [
  "dashboard/",
  "strategies/",
  "scripts/",
  "telegram/",
  "research/",
  "ops/",
  "infrastructure/",
  "deploy/",
  "execution/flatten_all.py",
  "execution/*bak*",
]

[lint.per-file-ignores]
"dashboard/dashboard_utils.py" = ["E402"]
"dashboard/main.py" = ["E402"]
